src/witan/app/handler.clj, src/witan/app/user.clj
the api should never provide the password hash. only white-listed data.
It also only ever returns one user, so returning an array makes no sense.
=> Fix/get only non-sensitive user data

src/witan/app/forecast.clj, src/witan/app/handler.clj, src/witan/app/schema.clj, src/witan/app/user.clj, test/witan/app/handler_test.clj
Also, removed `cors-mw` (we already use ring-cors) and run kibit + cljfmt
=> Adds `sweet/middlewares` to apply `token-auth-mw`

src/witan/app/forecast.clj
Because that's what the database expects
=> Replace `version_id` with `version` in query

cql/dev-schema.cql, cql/generate-staging-schema.sh, cql/staging-schema.cql, project.clj, src/witan/app/forecast.clj, src/witan/app/model.clj, src/witan/app/schema.clj, src/witan/app/test_data.clj, src/witan/app/util.clj, test/witan/app/forecast_test.clj
In this first approach, model properties can have 3 formats: text, number and dropdown.
When they are posted, they have to be checked for validity, and saved away with the forecast.
(first concrete example of this will be the London borough)
=> Save model property values with the forecast

cql/dev-schema.cql, src/witan/app/forecast.clj, src/witan/app/schema.clj
Two things here:
- fixed schema for property values
- added model id and properties to forecast versions
= Groundwork for the next feature to have full model information in the single version API
=> add model id and properties to forecast versions

cql/staging-schema.cql, src/witan/app/forecast.clj, src/witan/app/handler.clj, src/witan/app/model.clj, src/witan/app/schema.clj, test/witan/app/handler_test.clj
- Added model properties to the > 0 versions
- refactored a little bit
- service for /models/:id to retrieve model info
The input and output in the Forecast are stubbed to [] at the moment.
=> Schema changes to ForecastInfo to pass model props + /models/:id

src/witan/app/forecast.clj
Version 0 is uninteresting to us because it's a forecast that hasn't
been run. It's a limbo state for forecasts that require inputs and
therefore, once version one has been run, it should be deleted.
=> Delete 'version zero' when creating a version one

src/witan/app/s3.clj
Suggested by Neale, because get-object actually causes an open connection leak (unless you explicitly close it)
see https://github.com/weavejester/clj-aws-s3/commit/d249e174d715ab988b28e3caabfc491248678716
=> improvement to exists (avoiding connection leaks)

src/witan/app/forecast.clj, src/witan/app/util.clj
I discovered this bug by changing the conversion fn in utils to return
nil if the provided datetime was nil. Previously, this function would
return `(t/now)` which is erroneous.
=> Added `:created` to forecast headers.

cql/dev-schema.cql, src/witan/app/forecast.clj, src/witan/app/handler.clj, src/witan/app/schema.clj, src/witan/app/test_data.clj, test/witan/app/handler_test.clj
First step in running the model: saving the forecast versions with given inputs.
Assumption: we only save the inputs entered or chosen by the user, if an input is not supplied for one of the model's input categories, then we assume the default is used (if present).
=> First steps: run model api

src/witan/app/forecast.clj
Updated forecasts now get an appropriate `in-progress` and a fresh `created` timestamp
=> Fixed property bugs when updating forecasts

src/witan/app/forecast.clj
As you can see from the diff, they were stubbed previously so now we fetch them and coerce them into the correct format.
=> Inputs and Outputs now return the correct information

prepare-aws-creds
The regex for secrets is `(?<![A-Za-z0-9/+=])[A-Za-z0-9/+=]{40}(?![A-Za-z0-9/+=]).` (https://blogs.aws.amazon.com/security/blog/tag/key+rotation) so the belief is that the `@` will work as an appropriate delimiter.
=> Change `sed` delimiters to cope with slashes in AWS secrets

src/witan/app/forecast.clj
Double-check that all data is marked as public when we're uploading them to use in a public projection
=> Protect private data from going public

src/witan/app/data.clj, src/witan/app/demo_data.clj, src/witan/app/handler.clj, src/witan/app/test_data.clj
https://github.com/MastodonC/witan.ui/commit/35fea3fb65392bf2a00259f519ed51f17360c1c6
```
Added /data/public endpoint which 307's us to...
...S3 links if they exist in the public directory. This was implemented
to facilitate templates. By default, the endpoint will307 but passing
`redirect=false` as a query param will cause the link to be returned in
a JSON structure.
```
=> Added /data/public endpoint

circle.yml
Circle CI changes to deploy to new production
(environment variable DEPLOY_NEW_PRODUCTION_IP was added to witan.app in circle.ci and contains the elastic ip address for the deployment service on the new stack)
=> deploy to new production

project.clj, resources/dev.witan-app.edn, run_witan_app.sh, scripts/cqlsh.sh, scripts/kafka_console_consumer.sh, scripts/kafka_console_producer.sh, scripts/run_cassandra.sh, scripts/run_kafka.sh, src/witan/app/components/kafka.clj, src/witan/app/config.clj, src/witan/app/mq.clj, src/witan/app/schema.clj, src/witan/app/user.clj, src/witan/system.clj
You can now send messages to Kafka as _commands_ via `witan.app.mq/send-command!`
I've also included scripts to get a local Kafka up and running
=> Add Kafka boilerplate to witan.app

resources/email-templates/reset-your-password.html
I've used [inliner][], and [litmus][] to check how the HTML emails look in Google Chrome and Outlook 2013, the two most awkward of the popular email clients.
This makes the html look even messier than it did before, as the styles need to be declared inline.
[inliner]: http://foundation.zurb.com/emails/inliner.html
[litmus]: https://litmus.com
=> Add horrible inline styling for outlook and gmail

src/witan/validation.clj, test/witan/validation_test.clj
Encountered some data in the wild using "Borough Name" as a column header. This was slipping through validation and resulting in an error for users. The correct name for the column should be "Borough".
=> Update header validation

project.clj, resources/logback.xml, src/witan/app/handler.clj, src/witan/bootstrap.clj, src/witan/system.clj
simple logging with the appropriate format to be multilined and grokked correctly by our logstash stack
=> logging adapted to work with logstash setup (whiner-slf4j)
