MastodonC/witan.app

- project.clj
- src/witan/app/handler.clj
- test/witan/app/handler_test.clj
Using compojure-api and prismatic schema for validation.
(todo: use liberator - validation mostly in liberator)
> composure-api and schema used

- src/witan/app/handler.clj
Add the endpoints described in the doc:
https://docs.google.com/document/d/1MwH0dFnGB5iwpZ_etkjwzixpCa0dNJna-CfIznzoNvM/edit#
> Add the routes we will need for MVP1

- cql/dev-schema.cql
- cql/staging-schema.cql
- src/witan/app/handler.clj
- src/witan/app/user.clj
- test/witan/app/handler_test.clj
changed schema and corresponding routes to have better user table
> user with added name and id

- src/witan/app/config.clj
- src/witan/app/handler.clj
- src/witan/app/user.clj
- test/witan/app/handler_test.clj
when logged in, return user details
when not logged in, 401
> /me path to return user details when logged in

- Dockerfile
- project.clj
especially the resource file should be copied to home to be retrieved by the app. this should fix that.
> fix wrong assumptions about where things get copied

- project.clj
- resources/logback.xml
- src/witan/app/handler.clj
logging both to stdout and to syslog
> Adding logging to witan.app

- cql/dev-schema.cql
- project.clj
- src/witan/app/config.clj
- src/witan/app/forecast.clj
- src/witan/app/handler.clj
- src/witan/app/test_data.clj
- src/witan/app/user.clj
- src/witan/app/util.clj
- test/witan/app/handler_test.clj
This adds the `/forecasts` GET route into a Liberator resource.
> /forecasts route

- project.clj
- src/witan/app/handler.clj
There's also an `at-at` job to remove expired tokens.
> Tokens can now expire

- cql/dev-schema.cql
- src/witan/app/data.clj
- src/witan/app/model.clj
- src/witan/app/schema.clj
- src/witan/app/test_data.clj
First stab at getting started on the data items (input and output)
> Adding input and output data information to models

- src/witan/app/forecast.clj
- test/witan/app/handler_test.clj
quick fix to get-forecast function to be less convoluted
> more elegant get-forecast returning seq

- project.clj
- resources/dev.witan-app.edn
- resources/staging.witan-app.edn
- src/witan/app/handler.clj
- src/witan/app/s3.clj
- test/witan/app/s3_test.clj
getting presigned url for a file (giving file name as input param).
the presigned url gets retrieved with amazonica, and there's some post-processing to get something that works with s3-beam.
(reason: amazonica does a better job using amazon sdk and handling credentials)
> presigned url /data/pre-sign/:name

- src/witan/app/handler.clj
- src/witan/app/s3.clj
generate an uuid for every file we want to upload.
> no param but an uuid for the s3 key

- src/witan/app/data.clj
- src/witan/app/s3.clj
so that when downloading we have something recognizeable for the user
> having content-disposition header to have file name in presigned download URL

- cql/dev-schema.cql
- src/witan/app/data.clj
- src/witan/app/forecast.clj
Described here: https://github.com/MastodonC/witan.app/issues/56
> Fixes a bug where data items are duplicated

- src/witan/app/forecast.clj
- src/witan/app/test_data.clj
This indicates fn flags `in-progress?` as `false` and updates with the supplied outputs.
> Added `conclude-forecast!` function

- cql/dev-schema.cql
- src/witan/app/model.clj
- src/witan/app/schema.clj
- src/witan/app/test_data.clj
- test/witan/app/handler_test.clj
This predomindantly incurs changes to schema and model handling
> Models now have descriptions

- cql/dev-schema.cql
- src/witan/app/data.clj
- src/witan/app/model.clj
- src/witan/app/model_execution.clj
- src/witan/app/schema.clj
- src/witan/app/test_data.clj
- test/witan/app/model_execution_test.clj
models can have data sources which are not necessarily meant to be modified by the user.  So it's necessary to include them as model parameters, in a way.
> save fixed input data in the model

- cql/dev-schema.cql
- src/witan/app/forecast.clj
- src/witan/app/schema.clj
- src/witan/app/test_data.clj
- test/witan/app/handler_test.clj
This means that forecasts intrinsically know whether they are the later version or not, and gives us the opportunity to sign-post to the latest version.
> Added a 'latest?' field into forecasts

- src/witan/app/demo_data.clj
- src/witan/app/model_execution.clj
- test/witan/app/model_execution_test.clj
Valid demo data:
- users
- actual existing models
- all the necessary default inputs and fixed inputs
> demo input data

- src/witan/app/forecast.clj
Not sure why this was wrong but it was throwing further down the line; was expecting a hash-map, not a list of vectors
> Fixes the input structure for updating forecasts

- src/witan/app/data.clj
It was never incrementing the version number
> Fix to make data items version properly

- Dockerfile
- witan-app.json.template
port opened to allow connection to prod repl from the VPN
> expose repl port of docker instance

- src/witan/app/forecast.clj
It's automatically set by the projection
> Output data now has public or private flag

- src/witan/app/data.clj
- src/witan/app/handler.clj
If true, only public data is returned
> Added a query param to `data/:category`

- project.clj
- src/witan/app/model.clj
- src/witan/app/test_data.clj
> Model descriptions are now parsed as markdown

- project.clj
- resources/db-schema.cql
- src/witan/app/forecast.clj
- src/witan/app/model.clj
- src/witan/app/model_execution.clj
- src/witan/app/schema.clj
- src/witan/app/test_data.clj
- test/witan/app/handler_test.clj
- test/witan/app/model_execution_test.clj
- test/witan/app/smoke_test.clj
- New fertility data is added
- Models now download their own inputs
- Output structure has changed
> Add fertility fixed input data

- src/witan/app/test_data.clj
owner-data needs to be present in forecasts or schema complains
> required data in forecasts

- src/witan/app/forecast.clj
> Use `contains?` rather than `if-let`

- resources/db-schema.cql
- src/witan/app/forecast.clj
- test/witan/app/handler_test.clj
> Adds 'error' to forecast

- deploy_staging.sh
This reverts commit a8c6c8cce216a8db516aa04ded463eb56e2d8b18, reversing
changes made to 800adc99ee129022d31769e146855da7fef03d9c.
> Revert the change to the deploy_staging.sh script

- src/witan/app/test_data.clj
> Added description for trend model

- src/witan/app/test_data.clj
have fixed inputs assigned to the right models
> fixed inputs for ward models available for all the models

- resources/db-schema.cql
- src/witan/app/handler.clj
- src/witan/app/schema.clj
- src/witan/app/test_data.clj
- src/witan/app/user.clj
- src/witan/app/util.clj
- test/witan/app/handler_test.clj
Signup is only allowed if you've been assigned a token (temporary measure for first wave of users)
> signup with token only

- src/witan/app/user.clj
Extra action required: going through existing database and move all emails to lowercase
> emails should be case insensitive for invite

- src/witan/app/user.clj
all signed up users seem to have lower case so far so all good
> login also case insensitive

- src/witan/app/test_data.clj
- src/witan/app/user.clj
Whilst processing a CSV of invites, I made these changes to the fn to make it play nicer
> invite username clean moved and pair returned

- circle.yml
earlier circle.yml modification didn't work as expected, this should do it (and is more efficient)
> have built image deployed in one go

- src/witan/app/forecast.clj
This is currently just for use at the REPL
> Adds a fn to delete all versions of a forecast

- Dockerfile
- circle.yml
- prepare-aws-creds
- resources/aws-credentials.template
we used an extra user just to get the accesses we need, but the slave boxes already have sufficient permission to access S3
> use instance’s IAM role instead of inputting creds

- project.clj
- resources/db-schema.cql
- scripts/run_kafka.sh
- src/witan/app/email.clj
- src/witan/app/handler.clj
- src/witan/app/password_reset.clj
- src/witan/app/schema.clj
- src/witan/app/util.clj
- test/witan/app/handler_test.clj
- test/witan/app/smoke_test.clj
* Two new endpoints for dealing with password resets
* Token support in the db
> Add password reset feature

- witan-app.json.template
logstash.{{vpc-name}}-vpc.kixi
> logs to new logstash address

- witan-app.json.template
small addition to get environment in log fields
> add environment tag in log fields
